insert into moon_2040.resources (id, name, group_r, type_r, img, img_min) values
  (1, 'Колонисты', 3, 1, '/img/resources/PPL.png', '/img/resources/min/PPL.png'),
  (2, 'Кредиты', 1, 1, '/img/resources/Cr.png', '/img/resources/min/Cr.png'),
  (3, 'Еда', 1, 1, '/img/resources/Food.png', '/img/resources/min/Food.png'),
  (4, 'Кислород', 1, 1, '/img/resources/O2.png', '/img/resources/min/O2.png'),
  (5, 'Гелий-3', 1, 1, '/img/resources/He3.png', '/img/resources/min/He3.png'),
  (6, 'Минералы', 1, 1, '/img/resources/Min.png', '/img/resources/min/Min.png'),
  (7, 'Производственные материалы', 1, 1, '/img/resources/PMt.png', '/img/resources/min/PMt.png'),
  (8, 'Энергия', 1, 1, '/img/resources/En.png', '/img/resources/min/En.png'),
  (9, 'Ферма', 2, 2, '/img/resources/Ferm.png', '/img/resources/min/Ferm.png'),
  (10, 'Оксинизатор', 2, 2, '/img/resources/Ox.png', '/img/resources/min/Ox.png'),
  (11, 'Электростанция', 2, 2, '/img/resources/El.png', '/img/resources/min/El.png'),
  (12, 'Добывающая станция', 2, 2, '/img/resources/Ds.png', '/img/resources/min/Ds.png'),
  (13, 'Минеральная шахта', 2, 2, '/img/resources/Msh.png', '/img/resources/min/Msh.png'),
  (14, 'Завод материалов', 2, 2, '/img/resources/PPL.png', '/img/resources/min/PPL.png'),
  (15, 'Строительная артель', 2, 2, '/img/resources/Zmt.png', '/img/resources/min/Zmt.png'),
  (16, 'Жилой комплекс', 2, 2, '/img/resources/Gil.png', '/img/resources/min/Gil.png');